languages:
  chapter03:
    array-init: '/array.txt'
  chapter04:
    expression: '/expression.txt'
    expression-library: '/expression.txt'
    calculator: '/expression.txt'
    java-interface: '/Demo.java'
    rows: '/t.rows'
  chapter07:
    property-file: '/t.properties'
